# Generated by Django 5.1 on 2024-10-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_alter_persona_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sinopsis', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='static/peliculas/')),
                ('fecha', models.DateField()),
                ('calificacion', models.IntegerField()),
                ('trailer', models.CharField(max_length=150)),
            ],
        ),
    ]
