# Generated by Django 5.1 on 2024-10-17 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_rename_fecha_pelicula_fecha_lanzamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.BooleanField(default=False)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparto_peliculas', to='peliculas.pelicula')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparto_personas', to='peliculas.persona')),
            ],
        ),
    ]
